/*
-- Query: 
-- Date: 2015-12-19 18:36
*/
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Libro de texto');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Libro de Investigación');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Libro de registro');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Cuaderno');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Revista');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Agenda');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Almanaque');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Block');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Boletín');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Periódico');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Manual');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Catálogo');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Legajo');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Brochure');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Folleto');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Libreta');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Memoria');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Díptico');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Tríptico');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Cuadríptico');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Afiche');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Afiche-Díptico');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Afiche-Tríptico');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Afiche Cuadríptico');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Programa');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Encarte');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Volante');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Carátula');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Sticker');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Carné');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Certificado');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Constancia');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Credencial');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Diploma');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Fotocheck');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Tarjeta de Invitación');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Tarjeta de presentación');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Tarjeta conmemorativa');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Tarjeta de navidad');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Tarjeta de control');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Bolsa');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Caja');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Carpeta con bolsillo');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Carpeta sin bolsillo');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Sobres con membrete');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Sobres sin membrete');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Tapas y contratapas');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Tubos potadiploma');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'CD');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Folder de plástico');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Estuche de CD');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Cartilla');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Hoja membretada');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Ticket');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Recibo de movilidad');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Fichas');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Hojas de exámen');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'FUT');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Vale');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Impresión de carátulas');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Confección de libros');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Impresión');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Grabado de CD');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Banner');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'Serigrafiado');
INSERT INTO `tipo_trabajo` (`idtipo_trabajo`,`tip_nombre`) VALUES (NULL,'OTROS');
